### PR TITLE
added a comment about where the is gov filter is and removed extra IP…

### PR DESCRIPTION
**Pull request by ryrjanes**
I added a comment to what lines the filter is in both views (sessions and page_views).

Removed the extra IP addresses that seems to not be needed. Please confirm that.

### CODE REVIEW

**Comment by ryrjanes** [comment]
@mark-walle I have updated the views as suggested. Thanks

**Comment by mark-walle** [comment]
@ryrjanes you can also simplify the SQL statement a lot. I believe
```
${ip_address} LIKE '142.22.%' OR ${ip_address} LIKE '142.23.%' OR ${ip_address} LIKE '142.24.%' OR ${ip_address} LIKE '142.31.%' OR ${ip_address} LIKE '142.25.%' OR ${ip_address} LIKE '142.26.%' OR ${ip_address} LIKE '142.27.%' OR ${ip_address} LIKE '142.28.%' OR ${ip_address} LIKE '142.29.%' OR ${ip_address} LIKE '142.30.%' OR ${ip_address} LIKE '142.32.%' OR ${ip_address} LIKE '142.33.%' OR ${ip_address} LIKE '142.34.%' OR ${ip_address} LIKE '142.35.%' OR ${ip_address} LIKE '142.36.%' ;;
```
could be written as
```
${ip_address} LIKE '142.2[2-9]%.%' OR ${ip_address} LIKE '142.3[0-6]%.%';;
```
you may want to test that to confirm. This constrains the wildcard to look for a value in that range. you're looking at the second octet being constrained on those ranges `22-29` and `30-36`, followed by a `.%` to match . I think that covers them all.

**Comment by ryrjanes** [comment]
@mark-walle The logic for the change you suggested for the SQL doesn't work in looker and any changes will not make it more simple.  So I am unable to make that change.

**Comment by mark-walle** [comment]
@ryrjanes sorry, the case I provided was closer to POSIX regular expression matching, but Redshift docs say that's computationally expensive, so the conditional sequence of LIKE statements might be better anyway. https://docs.aws.amazon.com/redshift/latest/dg/pattern-matching-conditions-posix.html

Please re-order the IP addresses to be sequential, test again, and then I'll accept this PR.

**Comment by ryrjanes** [comment]
I have fixed the IP order. ready to be merged @mark-walle

**Pull request merged**
