### PR TITLE
Update page_views and sessions to incremental model

### PR DESCRIPTION
**Pull request by carabaestlein**
This PR updates the Snowplow web block's views to pull from the incremental version of the web model run via SQL Runner instead of creating their own PDTs.

### CODE REVIEW

**Comment by carabaestlein** [comment]
hey @danpollock I think this can probably also be merged now, although I don't think I have the permissions to do so!

**Comment by danpollock** [comment]
There are a few conflicts to resolve. 

Can you take a quick look @carabaestlein ?

**Comment by carabaestlein** [comment]
@danpollock I can see that there is conflicts, but unfortunately I can't see where as I don't have *write* access!

**Comment by carabaestlein** [comment]
Hi @danpollock, when I check in Looker it tells me there are still merge conflicts (even though I have pulled your changes)? Maybe you can merge here and if something breaks in the Looker views I can fix it!

**Comment by danpollock** [comment]
@carabaestlein: I tried to fix things, but I can't track it down. 

I'll merge here now (but not deploy to production until you get your fix in).

**Comment by danpollock** [comment]
@carabaestlein I merged it, but it really isn't happy now. 

Good luck!

**Comment by danpollock** [comment]
@carabaestlein: I've given you write permission on the repo in the hopes you can untangle the confusion the merge has brought.

**Comment by danpollock** [comment]
You can find the last "good" version in my branch dev-dan-pollock-djtj

**Pull request merged**
