### PR TITLE
Small update to the read me file to test the web hook.

### PR DESCRIPTION
**Pull request by ryrjanes**

### CODE REVIEW

**Comment by danpollock** [comment]
Why did you close the pull? 

(In case you didn't know, you can keep making changes inside the branch without closing the pull. Any further changes will be included when you finally complete the pull.)

**Comment by ryrjanes** [comment]
https://github.com/bcgov/GDX-Analytics-Looker/pull/3 

That is the correct pull.  I don't think I did it correctly so I did another one.

**Comment by danpollock** [comment]
In cases like this, leave the pull request open. 

If you are on the same branch, you should use the same pull request. 

You can continue to make changes to a branch without closing the request.

**Comment by danpollock** [comment]
It's much easier to follow if it's all in one request.

**Pull request closed without merging**
