### PR TITLE
Codev

### PR DESCRIPTION
**Pull request by hugoselbie**
Added in lookml to create the looker_email_analytics dashboard

### CODE REVIEW

**Comment by danpollock** [comment]
Hey @carabaestlein, here's the work Looker was doing, in case there are implications for the updates you're making. I believe we should be fine.

**Comment by carabaestlein** [comment]
hey @danpollock looks good to me! If there is any errors after merging we can always fix them :)

**Comment by danpollock** [comment]
Merging now. 

Thanks @hugoselbie and @carabaestlein !

**Comment by danpollock** [comment]
You can find the "last good" version before the attempted merge in my branch at dev-dan-pollock-djtj.

**Pull request merged**
